//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestsForFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestsForFramework.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \001_1.zip.
        /// </summary>
        internal static string bigFile {
            get {
                return ResourceManager.GetString("bigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 155.120.20.3.
        /// </summary>
        internal static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \001_1.zip.
        /// </summary>
        internal static string notImgFile {
            get {
                return ResourceManager.GetString("notImgFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 257646667.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \1.txt.
        /// </summary>
        internal static string txtFile {
            get {
                return ResourceManager.GetString("txtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user1.tat13@gmail.com.
        /// </summary>
        internal static string user1 {
            get {
                return ResourceManager.GetString("user1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user2.tat13@gmail.com.
        /// </summary>
        internal static string user2 {
            get {
                return ResourceManager.GetString("user2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user3.tat13@gmail.com.
        /// </summary>
        internal static string user3 {
            get {
                return ResourceManager.GetString("user3", resourceCulture);
            }
        }
    }
}
